#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

if [[ -d "${HOME}/.bashrc.d" ]]; then
    for f in ${HOME}/.bashrc.d/*.sh; do
        source "${f}"
    done
fi

